# eCommerce KPI Analysis

## Notebook 02 - Data Understanding

### Objective

Understand the structure, quality and relationships of the datasets before performing business analysis.

This notebook explores each table individually to identify:

- Number of observations
- Data types
- Missing values
- Duplicate records
- Potential data quality issues
- Initial business observations

### Author
Danae López Pérez

In [2]:
import pandas as pd
import numpy as np

In [3]:
DATA_PATH = "../data/raw/"

customers = pd.read_csv(DATA_PATH + "olist_customers_dataset.csv")

geolocation = pd.read_csv(DATA_PATH + "olist_geolocation_dataset.csv")

order_items = pd.read_csv(DATA_PATH + "olist_order_items_dataset.csv")

payments = pd.read_csv(DATA_PATH + "olist_order_payments_dataset.csv")

reviews = pd.read_csv(DATA_PATH + "olist_order_reviews_dataset.csv")

orders = pd.read_csv(DATA_PATH + "olist_orders_dataset.csv")

products = pd.read_csv(DATA_PATH + "olist_products_dataset.csv")

sellers = pd.read_csv(DATA_PATH + "olist_sellers_dataset.csv")

category_translation = pd.read_csv(DATA_PATH + "product_category_name_translation.csv")

In [ ]:
# CUSTOMER TABLE
# customers.shape # (99441, 5)
# customers.info()
# customers.isnull().sum()
# customers.duplicated().sum()

# customers["customer_unique_id"].nunique()
# customers["customer_city"].nunique()
# customers["customer_state"].nunique()

customers.head()

27

### Findings for Customer Table

- Primary Key: customer_id
- The dataset contains one record per customer.
- No missing values were detected.
- No duplicated rows were found.
- Customer IDs appear to be reliable.
- There's only 96096 unique customer id
- Supposedly we have 4119 different cities
- Supposedly we have 27 different states

In [ ]:
# GEOLOCATION TABLE
#geolocation.shape (1000163, 5)
#geolocation.info()
#geolocation.isnull().sum()
#geolocation.duplicated().sum() #(261831)

geolocation["geolocation_zip_code_prefix"].nunique() #19015
geolocation["geolocation_zip_code_prefix"].duplicated().sum() # the way to get the number of duplicates in a column
#geolocation.head()

19015

### Findings for Geolocation Table

- Primary Key: geolocation_zip_code_prefix	
- The dataset contains one record per zip code.
- No missing values were detected.
- 261831 duplicated rows were found.
- There's 19015 unique zip codes
- Supposedly we have 4119 different cities
- Supposedly we have 27 different states

The geolocation dataset contains 1,000,163 records but only 19,015 unique ZIP code prefixes. This indicates that each ZIP code can be associated with multiple geographic coordinates. Additionally, 261,831 rows are exact duplicates, meaning that all values in those records are identical. These duplicates should be evaluated before performing any geographic analysis to avoid redundant information.

In [39]:
# ORDER ITEMS TABLE
# order_items.shape # (112650, 7)
# order_items.info()
# order_items.isnull().sum()
# order_items.duplicated().sum()

order_items["order_id"].nunique() #98666
order_items["seller_id"].nunique()


order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

### Findings for Order Items Table

- Composite Primary Key: (order_id, order_item_id)
- The dataset contains one record for each item purchased within an order.
- No missing values were detected.
- No duplicated rows were found.
- A total of 98,666 unique orders are represented in this table.
- The dataset includes products sold by 3,095 unique sellers.

### Business Implications

- Since each row represents an individual item rather than a complete order, order-level KPIs such as Average Order Value or Revenue per Order will require aggregating the data by `order_id`.
- The presence of multiple sellers indicates that marketplace performance can be analyzed at both the order and seller levels.

In [20]:
# PAYMENTS ITEMS TABLE
# payments.shape # (103886, 5)
# payments.info()
# payments.isnull().sum()
# payments.duplicated().sum()
#payments["order_id"].nunique()
#payments["payment_type"].value_counts()
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

### Findings for Payments Table

- Composite Primary Key: (`order_id`, `payment_sequential`).
- The dataset contains one record for each payment transaction associated with an order.
- No missing values were detected.
- No duplicated rows were found.
- A total of five payment types are represented in this table. Credit card and boleto are the most frequently used payment methods.

In [ ]:
# REVIEWS TABLE
#reviews.shape # (99224, 7)
#reviews.info()
reviews.isnull().sum()
#reviews.duplicated().sum()
# reviews["order_id"].nunique()
# reviews["review_id"].nunique()

# reviews["review_score"].value_counts().sort_index()

# reviews.head()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

### Findings for Reviews Table

- Primary Key: `review_id`.
- The dataset contains one record for each review.
- Missing values are present only in the review title and review message fields, suggesting that many customers submitted ratings without written comments.
- No duplicated rows were found.

Review scores range from 1 to 5 stars.
Five-star reviews are the most common, followed by four-star reviews.
One-star reviews are considerably less frequent, while two- and three-star reviews represent a smaller share of the dataset.

In [ ]:
# ORDERS TABLE
orders.shape # (99441, 8)
orders.info()
orders.isnull().sum()
orders.duplicated().sum()
orders["order_id"].nunique()
orders["customer_id"].nunique()#99441

# reviews["review_score"].value_counts().sort_index()

#orders.head()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

99441

### Findings for Orders Table

- Primary Key: `order_id`.
- The dataset contains one record for each order.
- Missing values are present in the order approval, carrier delivery, and customer delivery timestamp columns.
- These missing values are expected for orders that were canceled or had not yet progressed through all fulfillment stages.
- No duplicated rows were found.

### Business Implications

- The timestamp columns allow the calculation of operational KPIs such as order processing time, shipping time, and delivery time.
- Missing delivery timestamps should be considered when analyzing logistics performance, as canceled or incomplete orders can bias delivery metrics if they are not filtered appropriately.

In [54]:
#PRODUCTS TABLE
# products.shape #(32951, 9)
# products.info()
# products.isnull().sum()
# products.duplicated().sum()

#products["product_id"].nunique()
#products["product_category_name"].nunique()
products["product_category_name"].value_counts().sort_index()

# reviews["review_score"].value_counts().sort_index()

#products.head()

product_category_name
agro_industria_e_comercio      74
alimentos                      82
alimentos_bebidas             104
artes                          55
artes_e_artesanato             19
                             ...
sinalizacao_e_seguranca        93
tablets_impressao_imagem        9
telefonia                    1134
telefonia_fixa                116
utilidades_domesticas        2335
Name: count, Length: 73, dtype: int64

### Findings for Products Table

- Primary Key: `product_id`.
- The dataset contains one record for each product.
- Missing values were found in the product category, product name length, product description length, product photo quantity, and product dimension attributes.
- Several products have missing catalog attributes.
- No duplicated rows were found.
- The dataset contains 32,951 unique products.
- We have 73 different categories.


### Business Implications
Products with incomplete catalog information may receive lower customer engagement due to the lack of descriptive content. Future analyses should evaluate whether missing product information is associated with lower sales performance or lower customer ratings.

In [ ]:
#SELLERS TABLE
sellers.shape #(3095, 4)
sellers.info()
sellers.isnull().sum()
sellers.duplicated().sum()

#sellers["seller_id"].nunique()
sellers["seller_state"].value_counts()
#sellers["seller_city"].nunique()

#sellers.head()

### Findings for Sellers Table

- Primary Key: `seller_id`.
- The dataset contains one record for each seller.
- No missing values were found.
- No duplicated rows were found.
- The dataset contains 3095 unique sellers.
- Most sellers are located in São Paulo (1,849 sellers).
- Registered sellers are distributed across 611 different cities.


### Business Implications
Visualize the geographic distribution of sellers across Brazil to identify regional concentrations and evaluate whether seller location influences sales performance, delivery times, or customer satisfaction.

### Potential Visualizations

- Choropleth map of sellers by state.
- Bar chart of the top 10 states by number of sellers.
- Bar chart of the top 20 cities with the highest number of sellers.

In [ ]:
#PRODUCT CATEGORY NAME TRANSLATION TABLE
category_translation.shape #(71, 2)
category_translation.info()
category_translation.isnull().sum()
category_translation.duplicated().sum()

category_translation["product_category_name"].nunique()

# category_translation.head()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

71

### Findings for Product Category Translation Table

- Primary Key: `product_category_name`.
- The dataset contains one record for each product category translation.
- The dataset provides English translations for product categories originally recorded in Portuguese.
- The dataset contains 71 category translations. However, the Products dataset contains 73 unique product categories, indicating that two categories do not have an English translation.
- No missing values were found.
- No duplicated rows were found.

### Business Implications

Before merging this table with the Products dataset, the missing category translations should be identified and handled appropriately. Untranslated categories may appear as missing values in reports or dashboards, potentially affecting category-level analyses.

In [73]:
set(products["product_category_name"].dropna()) - set(category_translation["product_category_name"])

{'pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos'}